### ISSUE TITLE
[Accepted] Provide configuration to change tab on MouseOver instead of MouseClick.

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#5]
It would be great if there is the possibility to define (in a config-file) if the tab switch by OnMouseOver or OnClick.
(IMHO with OnMouseOver it makes the navigation faster - and it is not disturbing, because the menu is at the top)

**Comment by Kevin-De-Coninck** [comment]
Just to let you know that you're request has been accepted and I'm working on it.

**Comment by Kevin-De-Coninck** [comment]
This issue has been resolved.

By default, the ribbon is configured in such a way so that the tabs does not change when you hover on it.
In case you want to change this, you can change the plugin's settings.
To change this, and thus enable changing the active tab when you hover on the tab, add the following code in your HTML:

    $.fn.OfficeUI.Defaults.changeActiveTabOnHover = false;
