### ISSUE TITLE
(high priority) Place a input-element for searching

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#7]
Hi,
I know this is no default Office2013 element, but i need a input-element as search-box.
It must always be accessible / visible - so I think top right is a good position.

In OfficeUI I have insert this:

````
<ul role="tablist">
 <div id="searchbox" style="position:absolute; right: 0;  background-color:#eee"><input value="search"> </div> 
 <li role="tab" class="application" id="tabFile">
````

Is this ok? Or do you know a better (code-) solution?
It is not necessary to implement this in OfficeUI.Beta, I need still a solution for my app.
But of course it can be helpful for someone else.

**Comment by Kevin-De-Coninck** [comment]
I'm still thinking about this one.
I'm not confident of putting an input element on every tab element.

Maybe I'll add a possibility to add a text-area instead of icons and then you can add it by specifying it in the OfficeUI ribbon.json file.

**Comment by Kevin-De-Coninck** [comment]
After some thinking about this one, I will not forsee an element that displays by default on every tab.
However, I've implemented a ribbon action type so that you can place an input element in the ribbon.

In order to do so, you'll have to create a new action in the ribbon.js as:

    {
        "Id": "inputText",
        "Legend": "Search criteria",
        "Type": "Input",
        "Width": "100px"
    }

If you do this, the input area in constructed in the ribbon like:

![image](https://cloud.githubusercontent.com/assets/3583827/5692358/c697af94-98f2-11e4-9526-40f75ca10a1d.png)

You'll see that the legend property is used as the placeholder and the width can be set if required.
When you start typing the text, the input element behaves like:

![image](https://cloud.githubusercontent.com/assets/3583827/5692360/e52746f4-98f2-11e4-8a85-b5adb05d0383.png)


Kind regards,
