### ISSUE TITLE
(very low priority) Tooltips for Icons

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#8]
like here:
http://okgodoit.com/ribbon/

Stay with the mouse over a icon.
Extend the JSON-file for a new optional attribut "tooltip-text"?

**Comment by Kevin-De-Coninck** [comment]
This issue is resolved.

Now it's possible to create a tooltip for icons on (both small and large).
The tooltip is defined on the action in the ribbon.json file.

    {
        "Id": "icoReply",
        "Resource": "/OfficeUI.Beta/Resources/Images/Ribbon/Tabs/Home/Reply.png",
        "Legend": "Reply",
        "Tooltip": "<strong>Reply (Ctrl+R)</strong><p>Reply to the sender of this message.</p>",
        "Type": "bIcon"
    }

The 'Tooltip' property takes HTML as input.
In order for the tooltip to show, move your mouse over the icon and wait for a second, the tooltip should then be showed like in the image below:

![image](https://cloud.githubusercontent.com/assets/3583827/5692669/d15144c0-98fe-11e4-91f9-c36fca1dfa18.png)
